### ISSUE TITLE
For some reason the produced message is not parsable by java clieet

### ISSUE THREAD

**Issue by yangou** [skulup/pulserl#12]
I've been trying to solve this problem by my own but still no luck.  
Not sure if this is because of the serialization because using official golang client results no issues at all.

Java client is able to parse the message metadata, but not the message payload
Steps to reproduce:
1. start the `bin/pulsar-client consume` command
2. produce the message to pulsar either in single message mode or in batched mode.

Errors out in java clinet
```
3:47:51.547 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [123.json][test] Subscribing to topic on cnx [id: 0x5a38b1b8, L:/127.0.0.1:52856 - R:localhost/127.0.0.1:6650], consumerId 0
13:47:51.561 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [123.json][test] Subscribed to topic on localhost/127.0.0.1:6650 -- consumer: 0
13:48:09.420 [pulsar-client-io-1-1] INFO  com.scurrilous.circe.checksum.Crc32cIntChecksum - SSE4.2 CRC32C provider initialized
----- got message -----
13:48:09.445 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - Error while consuming messages
13:48:09.445 [main] ERROR org.apache.pulsar.client.cli.PulsarClientTool - null
java.lang.NullPointerException: null
	at java.lang.String.<init>(String.java:566) ~[?:1.8.0_282]
	at org.apache.pulsar.client.cli.CmdConsume.interpretMessage(CmdConsume.java:155) ~[org.apache.pulsar-pulsar-client-tools-2.7.1.jar:2.7.1]
	at org.apache.pulsar.client.cli.CmdConsume.consume(CmdConsume.java:236) [org.apache.pulsar-pulsar-client-tools-2.7.1.jar:2.7.1]
	at org.apache.pulsar.client.cli.CmdConsume.run(CmdConsume.java:191) [org.apache.pulsar-pulsar-client-tools-2.7.1.jar:2.7.1]
	at org.apache.pulsar.client.cli.PulsarClientTool.run(PulsarClientTool.java:177) [org.apache.pulsar-pulsar-client-tools-2.7.1.jar:2.7.1]
	at org.apache.pulsar.client.cli.PulsarClientTool.main(PulsarClientTool.java:209) [org.apache.pulsar-pulsar-client-tools-2.7.1.jar:2.7.1]
```

**Comment by alphashaw** [comment]
Hello @yangou, thanks for exploring and reaching out.

Please, will you tell the **Apache Pulsar** version  and  **Java** client version with which you noticed the issue?

Thanks

**Comment by yangou** [comment]
Hi @alphashaw 
Sorry I should have closed this issue.  I found out it was bug in Pulsar itself, and filed PR on them.
